apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qs29cundt-python
  janus-idp.io/tekton: qs29cundt-python
  backstage.io/kubernetes-id: qs29cundt-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qs29cundt-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
